### ISSUE TITLE
webmozart/path-util is abandoned (required by vimeo/psalm:^4)

### ISSUE THREAD

**Issue by sereg-smile** [mortenson/psalm-plugin-drupal#14]
Hello,

webmozart/path-util package has been replaced in vimeo/psalm:^5 by symfony/filesystem.
it would be great if you can move to vimeo/psalm 5.

See https://github.com/vimeo/psalm/issues/7826

Thanks.

Have a good day,

Seb

**Comment by FlorentTorregrosa** [comment]
Hi,

I will try to provide a PR.

**Comment by FlorentTorregrosa** [comment]
PR #15 ready for review :)

**Comment by mortenson** [comment]
Thanks @FlorentTorregrosa ! Are you using this project or just trying it out?

**Comment by FlorentTorregrosa** [comment]
Thanks @mortenson for the quick merge.

Yes I am using it on projects.

It is in my project skeleton: https://gitlab.com/florenttorregrosa-drupal/docker-drupal-project

So all projects from my skeleton use it.

I count at least 5 projects at Smile using it + my personal website + my association website + the dev stacks I use to develop my contributed modules.

I plan, don't know when, to also add it in CI on drupal.org (at least for my modules).

The only usage drawback I have, and maybe one day if a solution can be found it would be great, is that dependencies needs to be explicitly listed in the XML config file + in the command line of `scripts/generate_entrypoint.php` the scanned modules to be explicitly listed. And I see myself and even more people using my skeleton (not knowing, but I am sure to have documented it somewhere)/forgetting to update the modules list.
